#! /bin/bash
#XML Datei aus dem Internet holen
cd /home/karl/bin
wget -O iss-data.xml "https://spotthestation.nasa.gov/sightings/indexrss.cfm?country=Germany&region=None&city=Ludwigshafen" 
#warte 1 Sekunde
sleep 1
# Gibt es in XML <descrition> , gibt ers auch einen Überflug
#Hole die Zeile , die mit date begint, und die nächsten 5 Zeilen (1mal)
#HTML- Klammern entfernen
#Grad-Symbol einfügen
#TABs am Zeilenanfang enfernen
#Übersetzen deutsch
#Speichern als Text

if grep -q  \<description\>  iss-data.xml
then  grep -A5 -m1 Date:  iss-data.xml | sed  -e 's/^[ \t]*//' | sed '{
s/&lt;br\/&gt;//
s/&#176/°/
s/Date/Am/
s/AM/früh/
s/PM/abends/
s/Time/Um/
s/Duration/Dauer/
s/less than/weniger als/
s/minut/Minut/
s/Maximum Elevation/Max. über Horizont/
s/Approach/Geht auf/
s/above/über/
s/Departure/Geht unter/
s/Monday/Montag/
s/Tuesday/Dienstag/
s/Wendsday/Mittwoch/
s/Tursday/Donnerstag/
s/Friday/Freitag/
s/Saturday/Samstag/
s/Sunday/Sonntag/
}' > iss-daten.txt 
issd=$(cat iss-daten.txt)
# Abfrage variable leer
if [ -z "${issd}" ]; then
issd=$(echo Gerade kein sichtbarer Überflug)
fi
#convert iss-photo1.png -fill white -stroke black -pointsize 20 -gravity center -annotate 10 -draw "text 32, 16 \"$issd\"" iss-daten.png
#convert iss-photo1.png -fill black -pointsize 20 -gravity center -draw "text 0,0\"$issd\"" iss-daten.png
convert iss-photo1.png -fill '#00688B' -weight Bold -pointsize 20 -gravity center -annotate 9 "$issd" iss-daten.png


sleep 3
#ftp-upload

HOST='domain.de'
USER='user'
PASSWD='secret'
FILE='iss-daten.png'
REMOTEPATH='/gagaga/images/XML2png'

#ftp upload
#ftp -n -p  $HOST <<END_SCRIPT
# quote USER $USER
# quote PASS $PASSWD
#binary
#cd $REMOTEPATH
#put $FILE
#bye
#quit
#END_SCRIPT

#copy
cp iss-daten.png /var/www/html/gagaga/images/autogenerated



#twittern
/usr/bin/perl /home/user/bin/ttytter.pl -status="Der nächste sichtbare ISS Überflug in Worms ist am: 
http://www.domain.de/home/xml2png.html"

#ftp-upload needs exit
exit
